#
# Master makefile for Miner source
#
# Makes all the executable by visiting subdirs and making there
#

LIBDIR = ..\main
#

CCFLAGS = /dNETWORK /dRELEASE /dNDEBUG

CLEAN_TARGS = $(OBJDIR)\*.obj

PROGS = lbmcomp

LBMCOMP_SRCS = lbmcomp.c 

LBMCOMP_LIBS = gr.lib misc.lib mem.lib iff.lib readfile.lib ui.lib io.lib func.lib cflib.lib cfile.lib 

LBMCOMP_LFLAGS = option stack=150k



