#
# Master makefile for Miner source
#
# Makes all the executable by visiting subdirs and making there
#

LIBDIR = ..\main
#

CCFLAGS = /dNETWORK /dRELEASE /dNDEBUG

CLEAN_TARGS = $(OBJDIR)\*.obj

PROGS = hogfile

HOGFILE_SRCS = hogfile.c 


